'use client';

import { useState } from 'react';
import { categories } from '@/entities/finance/model/mock-data';
import { useFinance } from '@/entities/finance/model/FinanceProvider';
import type { TransactionType } from '@/entities/finance/model/types';

export function TransactionForm({ onSaved, origin = 'Manual' }: { onSaved?: () => void; origin?: 'Manual' | 'Assistant' }) {
  const { dispatch } = useFinance(); const [type, setType] = useState<TransactionType>('expense'); const [amount, setAmount] = useState(''); const [merchant, setMerchant] = useState(''); const [category, setCategory] = useState('Comida'); const [error, setError] = useState('');
  const submit = (event: React.FormEvent) => { event.preventDefault(); const numericAmount = Number(amount); if (!merchant.trim() || !Number.isFinite(numericAmount) || numericAmount <= 0 || numericAmount > 1_000_000) { setError('Ingresa un comercio y un monto válido mayor que cero.'); return; } dispatch({ type: 'addTransaction', payload: { type, amount: numericAmount, merchant: merchant.trim().slice(0, 80), description: `Registro ${origin.toLowerCase()}`, category: type === 'income' ? 'Ingresos' : category, origin } }); onSaved?.(); };
  return <form onSubmit={submit} className="space-y-4"><div className="grid grid-cols-2 gap-2 rounded-xl bg-slate-100 p-1">{(['expense','income'] as TransactionType[]).map((item) => <button type="button" key={item} onClick={() => setType(item)} className={`rounded-lg py-2.5 text-sm font-bold ${type === item ? 'bg-white text-emerald-800 shadow-sm' : 'text-slate-500'}`}>{item === 'expense' ? 'Gasto' : 'Ingreso'}</button>)}</div><label className="block text-sm font-semibold">Monto<input inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0.00" className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-4 text-lg font-bold outline-none focus:border-emerald-500"/></label><label className="block text-sm font-semibold">Comercio o descripción<input value={merchant} onChange={(event) => setMerchant(event.target.value)} maxLength={80} placeholder="Ej. Supermercado" className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-4 text-sm outline-none focus:border-emerald-500"/></label>{type === 'expense' && <label className="block text-sm font-semibold">Categoría<select value={category} onChange={(event) => setCategory(event.target.value)} className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-4 text-sm">{categories.map((item) => <option key={item}>{item}</option>)}</select></label>}{error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<button className="h-12 w-full rounded-xl bg-emerald-800 font-bold text-white hover:bg-emerald-900">Guardar transacción</button></form>;
}
