'use client';

import { Bell, CheckCheck, Settings2, X } from 'lucide-react';
import { useFinance } from '@/entities/finance/model/FinanceProvider';

export function NotificationDrawer({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { notifications, preferences, dispatch } = useFinance();
  const unread = notifications.filter((item) => !item.read).length;
  const toggles = [{ key: 'budgetAlerts' as const, label: 'Alertas de presupuesto' },{ key: 'movementAlerts' as const, label: 'Ingresos y gastos' },{ key: 'insightAlerts' as const, label: 'Insights y recomendaciones' }];
  return <><button aria-label="Cerrar notificaciones" onClick={onClose} className={`fixed inset-0 z-40 bg-slate-950/25 transition-opacity ${open ? 'pointer-events-auto opacity-100' : 'pointer-events-none opacity-0'}`}/><aside className={`fixed inset-y-0 right-0 z-50 flex w-[min(94vw,31rem)] flex-col bg-white shadow-2xl transition-transform duration-300 dark:bg-slate-900 ${open ? 'translate-x-0' : 'translate-x-full'}`}>
    <div className="flex items-center justify-between border-b border-slate-100 p-5 dark:border-slate-700"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-emerald-50 text-emerald-700"><Bell size={20}/></span><div><h2 className="text-xl font-bold">Notificaciones</h2><p className="text-xs text-slate-500">Mantente al día con tus finanzas</p></div></div><button onClick={onClose} className="rounded-full p-2 hover:bg-slate-100"><X size={20}/></button></div>
    <div className="min-h-0 flex-1 overflow-y-auto p-5"><div className="flex items-center justify-between"><div className="flex gap-2"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">Todas {notifications.length}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">No leídas {unread}</span></div><button onClick={() => dispatch({ type: 'markNotificationsRead' })} className="flex items-center gap-1 text-xs font-semibold text-emerald-700"><CheckCheck size={15}/> Leer todas</button></div>
      <div className="mt-4 divide-y divide-slate-100 dark:divide-slate-700">{notifications.map((item) => <button key={item.id} onClick={() => dispatch({ type: 'toggleNotification', payload: item.id })} className="flex w-full gap-3 py-4 text-left"><span className={`mt-2 size-2 shrink-0 rounded-full ${item.read ? 'bg-slate-300 dark:bg-slate-600' : 'bg-emerald-600'}`}/><span><strong className="block text-sm text-slate-900 dark:text-slate-100">{item.title}</strong><span className="mt-1 block text-sm leading-5 text-slate-500">{item.description}</span><span className="mt-2 block text-slate-400">{item.date}</span></span></button>)}</div>
      <div className="mt-5 rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex items-center gap-2"><Settings2 size={18} className="text-violet-600"/><h3 className="font-bold">Preferencias</h3></div>{toggles.map((item) => <div key={item.key} className="mt-4 flex items-center justify-between gap-3 text-sm"><span className="text-slate-600 dark:text-slate-300">{item.label}</span><button role="switch" aria-checked={preferences[item.key]} onClick={() => dispatch({ type: 'updatePreferences', payload: { [item.key]: !preferences[item.key] } })} className={`relative h-6 w-11 rounded-full ${preferences[item.key] ? 'bg-emerald-700' : 'bg-slate-300 dark:bg-slate-600'}`}><span className={`absolute top-1 size-4 rounded-full bg-white transition-transform ${preferences[item.key] ? 'left-6' : 'left-1'}`}/></button></div>)}</div>
      <div className="mt-4 grid grid-cols-3 gap-2 rounded-2xl bg-linear-to-br from-emerald-50 to-lime-50 p-4 text-center"><span><strong className="block text-lg text-emerald-900">{notifications.length}</strong><span className="text-emerald-800/70">Totales</span></span><span><strong className="block text-lg text-emerald-900">{notifications.length-unread}</strong><span className="text-emerald-800/70">Leídas</span></span><span><strong className="block text-lg text-emerald-900">{unread}</strong><span className="text-emerald-800/70">Pendientes</span></span></div>
    </div>
  </aside></>;
}
