'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Check, FileSpreadsheet, Upload } from 'lucide-react';
import { useFinance } from '@/entities/finance/model/FinanceProvider';
import { AppCard } from '@/shared/components/AppCard';

const preview = [{ merchant: 'Supermercado Central', category: 'Comida', amount: 34.8, type: 'expense' as const },{ merchant: 'Transferencia recibida', category: 'Ingresos', amount: 420, type: 'income' as const },{ merchant: 'Estación de servicio', category: 'Transporte', amount: 28, type: 'expense' as const }];

export function ImportMovements({ locale }: { locale: 'es' | 'en' }) {
  const [step, setStep] = useState(1); const [fileName, setFileName] = useState(''); const { dispatch, formatMoney } = useFinance(); const router = useRouter();
  const confirm = () => { preview.forEach((item) => dispatch({ type: 'addTransaction', payload: { ...item, description: 'Importado desde archivo CSV', origin: 'CSV' } })); setStep(3); };
  return <div className="mx-auto max-w-4xl space-y-6"><div className="grid grid-cols-3 gap-2">{['Seleccionar','Revisar','Confirmar'].map((item,index) => <div key={item} className={`rounded-xl p-3 text-center text-xs font-bold ${step >= index + 1 ? 'bg-emerald-700 text-white' : 'bg-white text-slate-400'}`}>{index + 1}. {item}</div>)}</div><AppCard className="p-5 sm:p-8">{step === 1 && <div className="rounded-2xl border-2 border-dashed border-slate-200 p-10 text-center"><Upload className="mx-auto text-emerald-700" size={35}/><h2 className="mt-4 text-lg font-bold">Selecciona tu archivo CSV</h2><p className="mt-2 text-sm text-slate-500">Hasta 5 MB. La primera fila debe contener los encabezados.</p><label className="mt-6 inline-flex cursor-pointer rounded-xl bg-emerald-800 px-5 py-3 text-sm font-bold text-white">Elegir archivo<input type="file" accept=".csv,text/csv" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (file && file.size <= 5 * 1024 * 1024) { setFileName(file.name); setStep(2); } }}/></label></div>}{step === 2 && <><div className="mb-5 flex items-center gap-3 rounded-xl bg-emerald-50 p-4"><FileSpreadsheet className="text-emerald-700"/><span><strong className="block text-sm">{fileName}</strong><small className="text-slate-500">3 filas válidas · 0 errores</small></span></div><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs text-slate-500"><th className="p-3">Descripción</th><th className="p-3">Categoría</th><th className="p-3">Tipo</th><th className="p-3 text-right">Monto</th></tr></thead><tbody>{preview.map((item) => <tr key={item.merchant} className="border-b border-slate-100"><td className="p-3 font-semibold">{item.merchant}</td><td className="p-3">{item.category}</td><td className="p-3">{item.type === 'income' ? 'Ingreso' : 'Gasto'}</td><td className="p-3 text-right font-bold">{formatMoney(item.amount)}</td></tr>)}</tbody></table></div><div className="mt-6 flex justify-end gap-2"><button onClick={() => setStep(1)} className="rounded-xl border px-4 py-2 text-sm font-semibold">Cambiar archivo</button><button onClick={confirm} className="rounded-xl bg-emerald-800 px-5 py-2 text-sm font-bold text-white">Importar 3 movimientos</button></div></>}{step === 3 && <div className="py-10 text-center"><span className="mx-auto grid size-16 place-items-center rounded-full bg-emerald-100 text-emerald-700"><Check size={30}/></span><h2 className="mt-4 text-2xl font-bold">Importación completada</h2><p className="mt-2 text-slate-500">Los movimientos ya forman parte de tu resumen financiero.</p><button onClick={() => router.push(`/${locale}/dashboard/movimientos`)} className="mt-6 rounded-xl bg-emerald-800 px-5 py-3 text-sm font-bold text-white">Ver movimientos</button></div>}</AppCard></div>;
}
