'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowDown, ArrowUp, Download, Filter, MoreHorizontal, Search } from 'lucide-react';
import { useFinance } from '@/entities/finance/model/FinanceProvider';
import { AppCard } from '@/shared/components/AppCard';
import { MetricCard } from '@/shared/components/MetricCard';

export function Movements({ locale }: { locale: 'es' | 'en' }) {
  const { transactions, summary, formatMoney } = useFinance(); const [query, setQuery] = useState(''); const [type, setType] = useState('all'); const [category, setCategory] = useState('all'); const [origin, setOrigin] = useState('all');
  const filtered = useMemo(() => transactions.filter((item) => (type === 'all' || item.type === type) && (category === 'all' || item.category === category) && (origin === 'all' || item.origin === origin) && `${item.merchant} ${item.description} ${item.category}`.toLowerCase().includes(query.toLowerCase())), [transactions, query, type, category, origin]);
  const clear = () => { setQuery(''); setType('all'); setCategory('all'); setOrigin('all'); };
  return <div className="space-y-6">
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><MetricCard title="Ingresos del mes" value={formatMoney(summary.income)} icon={<ArrowDown size={19}/>}/><MetricCard title="Gastos del mes" value={formatMoney(summary.expenses)} tone="red" icon={<ArrowUp size={19}/>}/><MetricCard title="Saldo del mes" value={formatMoney(summary.balance)} icon={<ArrowDown size={19}/>}/><MetricCard title="Total movimientos" value={String(transactions.length)} tone="violet" icon={<MoreHorizontal size={19}/>}/></div>
    <AppCard className="overflow-hidden"><div className="grid gap-3 border-b border-slate-100 p-4 md:grid-cols-2 xl:grid-cols-[1.5fr_repeat(3,1fr)_auto]"><label className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar movimiento..." className="h-11 w-full rounded-xl border border-slate-200 pl-10 pr-3 text-sm outline-none focus:border-emerald-500"/></label><select value={type} onChange={(event) => setType(event.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option value="all">Todos los tipos</option><option value="income">Ingresos</option><option value="expense">Gastos</option></select><select value={category} onChange={(event) => setCategory(event.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option value="all">Todas las categorías</option>{[...new Set(transactions.map((item) => item.category))].map((item) => <option key={item}>{item}</option>)}</select><select value={origin} onChange={(event) => setOrigin(event.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option value="all">Todos los orígenes</option>{['Telegram','Manual','CSV','Assistant'].map((item) => <option key={item}>{item}</option>)}</select><button onClick={clear} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-emerald-200 px-4 text-sm font-semibold text-emerald-700"><Filter size={16}/>Limpiar</button></div>
      <div className="hidden max-h-[calc(100dvh-29rem)] min-h-72 overflow-auto md:block"><table className="w-full min-w-[800px] text-left text-sm"><thead className="sticky top-0 z-10 bg-slate-50 text-xs text-slate-500 shadow-[0_1px_0_#e2e8f0]"><tr>{['Fecha','Descripción','Categoría','Tipo','Monto','Origen',''].map((item) => <th key={item} className="px-5 py-4 font-semibold">{item}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((item) => <tr key={item.id} className="hover:bg-slate-50/70"><td className="px-5 py-4 text-xs text-slate-500">{new Date(item.date).toLocaleDateString('es-EC')}</td><td className="px-5 py-4"><strong className="block">{item.merchant}</strong><span className="text-xs text-slate-500">{item.description}</span></td><td className="px-5 py-4"><span className="rounded-lg bg-emerald-50 px-2 py-1 text-xs text-emerald-700">{item.category}</span></td><td className={`px-5 py-4 font-semibold ${item.type === 'income' ? 'text-emerald-700' : 'text-rose-600'}`}>{item.type === 'income' ? '↓ Ingreso' : '↑ Gasto'}</td><td className={`px-5 py-4 font-bold ${item.type === 'income' ? 'text-emerald-700' : 'text-slate-900'}`}>{item.type === 'income' ? '+' : '-'}{formatMoney(item.amount)}</td><td className="px-5 py-4 text-xs text-slate-500">{item.origin}</td><td className="px-5 py-4"><Link href={`/${locale}/dashboard/movimientos/${item.id}`} aria-label="Ver detalle"><MoreHorizontal size={18}/></Link></td></tr>)}</tbody></table></div>
      <div className="divide-y divide-slate-100 md:hidden">{filtered.map((item) => <Link href={`/${locale}/dashboard/movimientos/${item.id}`} key={item.id} className="flex items-center gap-3 p-4"><span className={`grid size-10 place-items-center rounded-full ${item.type === 'income' ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-600'}`}>{item.type === 'income' ? <ArrowDown size={18}/> : <ArrowUp size={18}/>}</span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{item.merchant}</strong><span className="text-slate-500">{item.category} · {item.origin}</span></span><strong className={item.type === 'income' ? 'text-emerald-700' : 'text-slate-900'}>{item.type === 'income' ? '+' : '-'}{formatMoney(item.amount)}</strong></Link>)}</div>
      {filtered.length === 0 && <div className="p-12 text-center text-slate-500">No encontramos movimientos con esos filtros.</div>}<div className="flex items-center justify-between border-t border-slate-100 p-4 text-xs text-slate-500"><span>Mostrando {filtered.length} movimientos</span><button className="flex items-center gap-2 font-semibold text-slate-700"><Download size={15}/>Exportar</button></div>
    </AppCard></div>;
}
