'use client';

import { useState } from 'react';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import { FileUp, MessageCircle, PenLine, Send, ShieldCheck, Sparkles } from 'lucide-react';
import { useFinance } from '@/entities/finance/model/FinanceProvider';
import { AppCard } from '@/shared/components/AppCard';
import { Modal } from '@/shared/components/Modal';
import { TransactionForm } from '@/features/transactions/components/TransactionForm';

export function NewTransaction({ locale }: { locale: 'es' | 'en' }) {
  const router = useRouter(); const { sendAssistantMessage, transactions, formatMoney } = useFinance();
  const [mode, setMode] = useState<'chat' | 'manual' | 'csv'>('chat'); const [message, setMessage] = useState(''); const [preview, setPreview] = useState<{ amount: number; merchant: string; category: string } | null>(null); const [manualOpen, setManualOpen] = useState(false); const [status,setStatus]=useState('');
  const parse = async () => { if(!message.trim())return;setStatus('Procesando con IA…');try{await sendAssistantMessage(message.trim());setStatus('Procesado correctamente. Los movimientos se actualizaron desde la base de datos.');setMessage('');setPreview(null);}catch(caught){setStatus(caught instanceof Error?caught.message:'No pudimos procesar el mensaje.');} };
  const confirm = () => undefined;
  const methods = [{ key: 'chat' as const, label: 'Conversando', text: 'Usa lenguaje natural con Kinti', icon: MessageCircle, tone: 'bg-emerald-50 text-emerald-700' }, { key: 'manual' as const, label: 'Manual', text: 'Completa un formulario paso a paso', icon: PenLine, tone: 'bg-blue-50 text-blue-700' }, { key: 'csv' as const, label: 'Importar CSV', text: 'Desde tu banco u otro archivo', icon: FileUp, tone: 'bg-violet-50 text-violet-700' }];
  return <div className="space-y-6">
    {status && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{status}</p>}
    <div className="grid gap-4 xl:grid-cols-[1fr_22rem]"><AppCard className="p-5 sm:p-7"><h2 className="text-lg font-bold">1. Elige cómo quieres registrar</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{methods.map(({ key, label, text, icon: Icon, tone }) => <button key={key} onClick={() => { setMode(key); if (key === 'manual') setManualOpen(true); if (key === 'csv') router.push(`/${locale}/dashboard/movimientos/importar`); }} className={`rounded-2xl border p-4 text-left ${mode === key ? 'border-emerald-500 bg-emerald-50/50' : 'border-slate-200'}`}><span className={`grid size-10 place-items-center rounded-full ${tone}`}><Icon size={19}/></span><strong className="mt-3 block">{label}</strong><span className="mt-1 block leading-5 text-slate-500">{text}</span></button>)}</div><h2 className="mt-8 text-lg font-bold">2. Cuéntale a Kinti</h2><p className="mt-1 text-sm text-slate-500">Escribe como lo harías normalmente: “Gasté 25 dólares en comida”.</p><div className="mt-4 rounded-2xl border border-slate-200 p-3"><textarea value={message} onChange={(event) => setMessage(event.target.value)} maxLength={200} placeholder="Ej: Gasté 25 dólares en comida en McDonald's" className="min-h-28 w-full resize-none p-2 text-sm outline-none"/><div className="flex justify-end"><button disabled={!message.trim()} onClick={parse} className="grid size-11 place-items-center rounded-xl bg-emerald-800 text-white disabled:opacity-40"><Send size={19}/></button></div></div>{preview && <div className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><p className="mb-3 font-bold text-emerald-900">Revisa lo que entendí</p><div className="grid grid-cols-3 gap-2 text-sm"><span><span className="block text-slate-500">Monto</span>${preview.amount.toFixed(2)}</span><span><span className="block text-slate-500">Comercio</span>{preview.merchant}</span><span><span className="block text-slate-500">Categoría</span>{preview.category}</span></div><div className="mt-4 flex justify-end gap-2"><button onClick={() => setPreview(null)} className="rounded-lg border px-4 py-2 text-sm font-semibold">Editar</button><button onClick={confirm} className="rounded-lg bg-emerald-800 px-4 py-2 text-sm font-bold text-white">Confirmar</button></div></div>}</AppCard>
      <AppCard className="relative min-h-[30rem] overflow-hidden p-5"><h2 className="text-lg font-bold">¿Cómo funciona?</h2>{[{ icon: MessageCircle, title: 'Escribe tu mensaje', text: 'Cuéntale a Kinti tu ingreso o gasto.' },{ icon: Sparkles, title: 'Kinti lo entiende', text: 'La demo interpreta los detalles principales.' },{ icon: ShieldCheck, title: 'Revisa y confirma', text: 'Nada se guarda sin tu aprobación.' }].map(({ icon: Icon, title, text }, index) => <div key={title} className="relative z-10 mt-6 flex gap-3"><span className={`grid size-9 shrink-0 place-items-center rounded-full ${index === 0 ? 'bg-emerald-50 text-emerald-700' : index === 1 ? 'bg-violet-50 text-violet-700' : 'bg-orange-50 text-orange-700'}`}><Icon size={17}/></span><span><strong className="text-sm">{title}</strong><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></span></div>)}<Image src="/assets/login/kinti-bird.png" alt="" width={110} height={100} className="absolute bottom-14 right-8 z-10 w-24 object-contain"/><Image src="/assets/app/leaves.svg" alt="" width={220} height={150} className="absolute -bottom-5 -right-8 w-52 opacity-75"/></AppCard></div>
    <AppCard className="p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">3. Transacciones recientes</h2><button onClick={() => router.push(`/${locale}/dashboard/movimientos`)} className="text-sm font-semibold text-emerald-700">Ver todas</button></div><div className="grid gap-3 md:grid-cols-3">{transactions.slice(0,3).map((item) => <div key={item.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex items-center justify-between"><span><strong className="block text-sm">{item.merchant}</strong><span className="text-slate-500">{item.category}</span></span><strong className={item.type === 'income' ? 'text-emerald-700' : 'text-rose-600'}>{item.type === 'income' ? '+' : '-'}{formatMoney(item.amount)}</strong></div></div>)}</div></AppCard>
    <Modal open={manualOpen} onCloseAction={() => setManualOpen(false)} title="Registro manual"><TransactionForm onSavedAction={() => router.push(`/${locale}/dashboard/movimientos`)}/></Modal>
  </div>;
}
