'use client';
import { BarChart3, CalendarDays, PiggyBank, Target, TrendingUp } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useFinance } from '@/entities/finance/model/FinanceProvider';
import { AppCard } from '@/shared/components/AppCard';
import { MetricCard } from '@/shared/components/MetricCard';
const colors=['#15803d','#7c3aed','#f59e0b','#f43f5e','#3b82f6','#94a3b8'];
export function Insights(){
 const {summary,previousSummary,transactions,expensesByCategory,formatMoney}=useFinance();const now=new Date();const daysInMonth=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();const elapsed=Math.max(1,now.getDate());
 const data=Object.entries(expensesByCategory).map(([name,value],index)=>({name,value,fill:colors[index%colors.length]}));const largest=[...data].sort((a,b)=>b.value-a.value)[0];const savings=summary.income?Math.round(summary.balance/summary.income*100):0;const previousSavings=previousSummary.income?Math.round(previousSummary.balance/previousSummary.income*100):0;
 const daily=Array.from({length:elapsed},(_,index)=>{const day=index+1;const through=transactions.filter(item=>new Date(item.date).getDate()<=day);return{day:String(day),income:through.filter(item=>item.type==='income').reduce((sum,item)=>sum+item.amount,0),expense:through.filter(item=>item.type==='expense').reduce((sum,item)=>sum+item.amount,0)}});
 const byWeekday=Array.from({length:7},(_,day)=>({day:new Intl.DateTimeFormat('es',{weekday:'short'}).format(new Date(2026,5,1+day)),value:transactions.filter(item=>item.type==='expense'&&((new Date(item.date).getDay()+6)%7)===day).reduce((sum,item)=>sum+item.amount,0)}));
 const expenseDays=new Map<number,number>();transactions.filter(item=>item.type==='expense').forEach(item=>{const day=new Date(item.date).getDate();expenseDays.set(day,(expenseDays.get(day)??0)+item.amount)});const average=summary.expenses/Math.max(expenseDays.size,1);const below=[...expenseDays.values()].filter(value=>value<average).length;const projection=summary.expenses/elapsed*daysInMonth;const balanceChange=previousSummary.balance?`${((summary.balance-previousSummary.balance)/Math.abs(previousSummary.balance)*100).toFixed(1)}% vs. mes anterior`:'Sin comparación anterior';
 const insight=largest?`${largest.name} concentra ${summary.expenses?Math.round(largest.value/summary.expenses*100):0}% de tus gastos del mes.`:'Registra movimientos para generar insights.';const recommendations=[summary.expenses>summary.income?'Prioriza reducir gastos hasta recuperar un balance positivo.':`Tu balance del mes es ${formatMoney(summary.balance)}.`,largest?`Revisa los movimientos de ${largest.name}, tu categoría de mayor gasto.`:'Importa o registra movimientos para obtener recomendaciones.',transactions.length<5?'Más registros mejorarán la precisión de las comparaciones.':'Mantén tus movimientos al día para conservar comparaciones útiles.'];
 return <div className="space-y-6"><div className="grid grid-cols-2 gap-3 lg:grid-cols-3 2xl:grid-cols-5"><MetricCard title="Balance del periodo" value={formatMoney(summary.balance)} detail={balanceChange} trend={daily.map(item=>item.income-item.expense)} icon={<TrendingUp size={19}/>}/><MetricCard title="Tasa de ahorro" value={`${savings}%`} detail={`${savings-previousSavings} p.p. vs. mes anterior`} trend={daily.map(item=>item.income?Math.round((item.income-item.expense)/item.income*100):0)} icon={<PiggyBank size={19}/>}/><MetricCard title="Mayor categoría" value={largest?.name??'—'} detail={largest?formatMoney(largest.value):'Sin gastos'} trend={data.map(item=>item.value)} tone="orange" icon={<BarChart3 size={19}/>}/><MetricCard title="Días bajo el promedio" value={`${below} días`} detail={`De ${expenseDays.size} días con gastos`} trend={[...expenseDays.values()]} tone="violet" icon={<CalendarDays size={19}/>}/><MetricCard title="Proyección fin de mes" value={formatMoney(projection)} detail={`Estimado al ${daysInMonth} de ${new Intl.DateTimeFormat('es',{month:'long'}).format(now)}`} trend={daily.map(item=>item.expense)} tone="violet" icon={<Target size={19}/>} /></div><div className="grid gap-4 xl:grid-cols-[1.15fr_1fr_.6fr]"><AppCard className="p-5"><h2 className="font-bold">Evolución de ingresos y gastos</h2><div className="mt-4 h-72"><ResponsiveContainer><AreaChart data={daily}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="day"/><YAxis/><Tooltip/><Legend/><Area dataKey="income" name="Ingresos" stroke="#15803d" fill="#15803d" fillOpacity={.12}/><Area dataKey="expense" name="Gastos" stroke="#f43f5e" fill="#f43f5e" fillOpacity={.1}/></AreaChart></ResponsiveContainer></div></AppCard><AppCard className="p-5"><h2 className="font-bold">Gastos por categoría</h2><div className="h-72"><ResponsiveContainer><PieChart><Pie data={data} dataKey="value" innerRadius="45%" outerRadius="70%"/><Tooltip formatter={(value)=>formatMoney(Number(value))}/><Legend/></PieChart></ResponsiveContainer></div></AppCard><AppCard className="bg-emerald-50 p-5"><span className="text-xs font-bold uppercase text-emerald-700">Insight destacado</span><h2 className="mt-5 text-lg font-bold text-emerald-950">{insight}</h2></AppCard></div><div className="grid gap-4 lg:grid-cols-2"><AppCard className="p-5"><h2 className="font-bold">Distribución por día</h2><div className="mt-4 h-64"><ResponsiveContainer><BarChart data={byWeekday}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="day"/><YAxis/><Tooltip/><Bar dataKey="value" fill="#7c3aed"/></BarChart></ResponsiveContainer></div></AppCard><AppCard className="p-5"><h2 className="font-bold">Recomendaciones prudentes</h2><div className="mt-4 space-y-3">{recommendations.map(text=><p key={text} className="rounded-xl bg-slate-50 p-4 text-sm">{text}</p>)}</div><p className="mt-4 text-xs text-slate-400">Información educativa; no constituye asesoría de inversión.</p></AppCard></div></div>;
}
