'use client';

import { useRef, useState } from 'react';
import { categories } from '@/entities/finance/model/categories';
import { useFinance } from '@/entities/finance/model/FinanceProvider';

export function BudgetForm({ onSavedAction: onSaved }: { onSavedAction: () => void }) {
  const { dispatch, budgets } = useFinance(); const available = categories.filter((item) => !budgets.some((budget) => budget.category === item)); const [category, setCategory] = useState<string>(available[0] ?? 'Otros'); const [limit, setLimit] = useState(''); const [threshold, setThreshold] = useState('80'); const [error, setError] = useState(''); const [isSubmitting, setIsSubmitting] = useState(false); const submitLock = useRef(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (submitLock.current) return; const amount = Number(limit); const warning = Number(threshold); if (!amount || amount <= 0 || warning < 1 || warning > 100) { setError('Ingresa un límite válido y un umbral entre 1 y 100.'); return; } submitLock.current = true; setIsSubmitting(true); setError(''); try { await dispatch({ type: 'saveBudget', payload: { category, limit: amount, threshold: warning, icon: '◉', color: '#15803d' } }); onSaved(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No pudimos guardar el presupuesto.'); } finally { submitLock.current = false; setIsSubmitting(false); } };
  return <form onSubmit={submit} className="space-y-4"><label className="block text-sm font-semibold">Categoría<select value={category} onChange={(event) => setCategory(event.target.value)} disabled={isSubmitting} className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-4 disabled:opacity-60">{available.length ? available.map((item) => <option key={item}>{item}</option>) : <option>Otros</option>}</select></label><label className="block text-sm font-semibold">Límite mensual<input value={limit} onChange={(event) => setLimit(event.target.value)} disabled={isSubmitting} inputMode="decimal" placeholder="500.00" className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-4 disabled:opacity-60"/></label><label className="block text-sm font-semibold">Avisarme al porcentaje<input value={threshold} onChange={(event) => setThreshold(event.target.value)} disabled={isSubmitting} type="number" min="1" max="100" className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-4 disabled:opacity-60"/></label>{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<button type="submit" disabled={isSubmitting} aria-busy={isSubmitting} className="h-12 w-full rounded-xl bg-emerald-800 font-bold text-white disabled:cursor-not-allowed disabled:opacity-60">{isSubmitting ? 'Guardando…' : 'Crear presupuesto'}</button></form>;
}
