'use client';

import { useEffect, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, Globe2, Menu, Moon, Sun, X } from 'lucide-react';
import type { HomeDictionary } from '@/shared/i18n/dictionaries/home';

export function LandingNav({ dict, locale, darkMode, onThemeAction, onDemoAction }: { dict: HomeDictionary; locale: 'es' | 'en'; darkMode: boolean; onThemeAction: () => void; onDemoAction: () => void }) {
  const [compact, setCompact] = useState(false); const [open, setOpen] = useState(false);
  useEffect(() => { const update = () => setCompact(window.scrollY > 24); update(); window.addEventListener('scroll', update, { passive: true }); return () => window.removeEventListener('scroll', update); }, []);
  const links = [{ target: 'producto', label: dict.navFeatures },{ target: 'como-funciona', label: dict.navHow },{ target: 'seguridad', label: dict.navSecurity }];
  const goToSection = (target: string) => { document.getElementById(target)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); setOpen(false); };
  return <header className="fixed inset-x-0 top-0 z-50 py-2 transition-all duration-500"><div className={`mx-auto flex w-[calc(100%-1rem)] items-center justify-between rounded-2xl px-3 py-0 transition-all duration-500 dark:text-white sm:w-[min(94%,86rem)] sm:px-5 ${compact ? 'border border-emerald-100/50 bg-[linear-gradient(135deg,rgba(220,252,231,.55),rgba(236,253,245,.32))] shadow-[0_16px_50px_rgba(8,59,44,.12)] backdrop-blur-2xl saturate-150 dark:border-emerald-200/10 dark:bg-[linear-gradient(135deg,rgba(6,78,59,.55),rgba(2,44,34,.38))]' : 'border border-transparent bg-transparent'}`}>
    <Link href={`/${locale}`} className="flex h-12 min-w-0 items-center gap-1.5 sm:h-14 sm:gap-4"><Image src="/assets/brand/kinti-bird.png" alt="Kinti" width={80} height={56} className="h-10 w-12 shrink-0 object-contain drop-shadow-[0_3px_5px_rgba(255,255,255,.95)] dark:drop-shadow-none sm:h-14 sm:w-20 sm:scale-125"/><span className="text-[2rem] font-black leading-none tracking-[-.05em] text-[#073d2d] [text-shadow:0_3px_5px_rgba(255,255,255,1),0_0_12px_rgba(255,255,255,.85)] dark:text-emerald-100 dark:[text-shadow:none] sm:text-[3.5rem]">kinti</span></Link>
    <nav className="hidden items-center gap-8 lg:flex">{links.map((item) => <button type="button" key={item.target} onClick={() => goToSection(item.target)} className="text-sm font-semibold text-slate-600 hover:text-emerald-800 dark:text-slate-300 dark:hover:text-emerald-300">{item.label}</button>)}</nav>
    <div className="hidden items-center gap-1.5 sm:flex"><Link href={locale === 'es' ? '/en' : '/es'} aria-label={locale === 'es' ? 'Idioma actual: Español. Cambiar a inglés' : 'Current language: English. Switch to Spanish'} className="flex h-10 items-center gap-1.5 rounded-xl border border-emerald-900/10 px-2.5 text-emerald-900 hover:bg-white/70 dark:border-white/10 dark:text-emerald-200 dark:hover:bg-white/10"><Globe2 size={18}/><span className="text-xs font-black">{locale.toUpperCase()}</span></Link><button type="button" onClick={onThemeAction} aria-label={darkMode ? 'Activar modo claro' : 'Activar modo oscuro'} className="grid size-10 place-items-center rounded-xl border border-emerald-900/10 text-emerald-900 hover:bg-white/70 dark:border-white/10 dark:text-emerald-200 dark:hover:bg-white/10">{darkMode ? <Sun size={18}/> : <Moon size={18}/>}</button><Link href={`/${locale}/login`} className="rounded-xl px-3 py-2.5 text-sm font-bold text-emerald-900 hover:bg-white/70 dark:text-emerald-100 dark:hover:bg-white/10">{dict.login}</Link><button onClick={onDemoAction} className="flex items-center gap-2 rounded-xl bg-[#075b40] px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-emerald-900/10 hover:-translate-y-0.5 hover:bg-[#064c36]">{dict.viewDemo}<ArrowUpRight size={16}/></button></div>
    <button onClick={() => setOpen((value) => !value)} className="grid size-10 shrink-0 place-items-center rounded-xl text-emerald-900 hover:bg-white/70 sm:hidden" aria-label={open ? 'Cerrar navegación' : 'Abrir navegación'}>{open ? <X/> : <Menu/>}</button>
  </div>{open && <div className="mx-auto mt-2 w-[min(92%,30rem)] rounded-2xl border border-emerald-100 bg-white/95 p-3 shadow-xl backdrop-blur-xl dark:border-white/10 dark:bg-slate-950/95 sm:hidden">{links.map((item) => <button type="button" onClick={() => goToSection(item.target)} key={item.target} className="block w-full rounded-xl px-4 py-3 text-left font-semibold text-slate-700 hover:bg-emerald-50 dark:text-slate-200 dark:hover:bg-white/10">{item.label}</button>)}<div className="my-2 grid grid-cols-2 gap-2"><Link href={locale === 'es' ? '/en' : '/es'} className="flex items-center justify-center gap-2 rounded-xl border border-emerald-200 py-2.5 text-sm font-bold text-emerald-800 dark:border-white/10 dark:text-emerald-200"><Globe2 size={17}/>{locale === 'es' ? 'English' : 'Español'}</Link><button type="button" onClick={onThemeAction} className="flex items-center justify-center gap-2 rounded-xl border border-emerald-200 py-2.5 text-sm font-bold text-emerald-800 dark:border-white/10 dark:text-emerald-200">{darkMode ? <Sun size={17}/> : <Moon size={17}/>}Tema</button></div><div className="grid grid-cols-2 gap-2"><Link href={`/${locale}/login`} className="rounded-xl border border-emerald-200 px-3 py-3 text-center text-sm font-bold text-emerald-800 dark:border-white/10 dark:text-emerald-200">{dict.login}</Link><button onClick={onDemoAction} className="rounded-xl bg-emerald-800 px-3 py-3 text-sm font-bold text-white">{dict.viewDemo}</button></div></div>}</header>;
}
